version: '3.4'

services:
  webapi:
    container_name: netvexanh.api
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - database
    networks:
      - implement-net

  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: netvexanh.database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Netvexanh2024!
      - MSSQL_PID=Express
    ports:
      - "1444:1433"
    networks: 
    - implement-net
    volumes:
      - NetVeXanh:/var/opt/mssql

volumes:
    NetVeXanh:
networks: 
  implement-net:
    driver: bridge