version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: netvexanh.api
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000;https://+:5001
      DefaultConnection: "Server=db-server;Database=mydatabase;User=sa;Password=your_password;"
    volumes:
      - ./WebAPI/localhost.pfx:/https/localhost.pfx


  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: netvexanh.database
    environment:
      - ACCEPT_EULA= "Y"
      - SA_PASSWORD= "YourComplexPassword123!"
    ports:
      - "1433:1433"